version: '2.1'

services:
  postgres:
    restart: always
    image: postgres:14.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: micronaut-playground
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_SCHEMA: micronaut-playground
